version: 2
updates:
  - package-ecosystem: "npm"
    commit-message:
      prefix: "[npm] "
    directories:
      - "/"
      - "/services/client"
      - "/services/server"
      - "/test/stress-test"
    schedule:
      interval: "weekly"
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
      version-bump:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: "docker"
    commit-message:
      prefix: "[docker] "
    directories:
      - "/services/"
      - "/test/stress-test"
    schedule:
      interval: "weekly"
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
      version-bump:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
