version: 2
updates:
  - package-ecosystem: "npm"
    commit-message:
      prefix: "[NPM] "
    directories:
      - "/"
      - "/services/client"
      - "/services/server"
      - "/test/stress-test"
    schedule:
      interval: "weekly"
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
      vite:
        patterns:
          - "*vite*"
        update-types:
          - minor
          - patch
      trpc:
        patterns:
          - "*trpc*"
        update-types:
          - minor
          - patch
      sentry:
        patterns:
          - "*sentry*"
        update-types:
          - minor
          - patch
      prisma:
        patterns:
          - "*prisma*"
        update-types:
          - minor
          - patch
      react:
        patterns:
          - "*react*"
        update-types:
          - minor
          - patch
      bump:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      major-vite:
        patterns:
          - "*vite*"
      major-trpc:
        patterns:
          - "*trpc*"
      major-sentry:
        patterns:
          - "*sentry*"
      major-prisma:
        patterns:
          - "*prisma*"
      major-react:
        patterns:
          - "*react*"
      major-bump:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    commit-message:
      prefix: "[DOCKER] "
    directories:
      - "/services/"
      - "/test/stress-test"
    schedule:
      interval: "monthly"
    groups:
      bump:
        patterns:
          - "*"
