version: 2
updates:
  - package-ecosystem: "npm"
    commit-message:
      prefix: "[NPM] "
    directories:
      - "/"
      - "/services/client"
      - "/services/server"
      - "/test/stress-test"
    schedule:
      interval: "weekly"
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
      vite:
        patterns:
          - "*vite*"
      trpc:
        patterns:
          - "*trpc*"
      sentry:
        patterns:
          - "*sentry*"
      prisma:
        patterns:
          - "*prisma*"
      react:
        patterns:
          - "*react*"
      bump:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: "npm"
    commit-message:
      prefix: "[NPM MAJOR] "
    directories:
      - "/"
      - "/services/client"
      - "/services/server"
      - "/test/stress-test"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch

  - package-ecosystem: "docker"
    commit-message:
      prefix: "[DOCKER] "
    directories:
      - "/services/"
      - "/test/stress-test"
    schedule:
      interval: "monthly"
    groups:
      bump:
        patterns:
          - "*"
