apiVersion: v1
kind: Secret
metadata:
  name: secret-database
  namespace: fs-project
data:
  # echo -n 'postgresql://root@cockroachdb-public.cockroachdb:26257/db-dev-all?schema=public' | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3Jvb3RAY29ja3JvYWNoZGItcHVibGljLmNvY2tyb2FjaGRiOjI2MjU3L2RiLWRldi1hbGw/c2NoZW1hPXB1YmxpYw==
