services:
  dev-db:
    image: postgres:17.0-alpine3.20
    container_name: postgres-dev
    ports:
      - '127.0.0.1:5433:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgresdevdb:/var/lib/postgresql/data

volumes:
  postgresdevdb:
