services:
  dev-db:
    image: postgres:17.0-alpine3.20
    container_name: dev-db
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    user: postgres
    volumes:
      - devdb:/var/lib/postgresql/data

volumes:
  devdb:
