services:
  dev-db:
    extends:
      file: ./docker-compose.dev-db-only.yml
      service: dev-db
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "cockroach sql --insecure --host=dev-db --execute 'SELECT 1'",
        ]
      interval: 5s
      timeout: 5s
      retries: 12
  dev-server:
    build:
      context: ../services
      dockerfile: dev.Dockerfile
    working_dir: /usr/src/app/server
    command: npm run dev
    container_name: dev-server
    network_mode: host
    depends_on:
      dev-db:
        condition: service_healthy
    env_file:
      - ../services/server/.env
    develop:
      watch:
        - action: sync
          path: ../services/server/src
          target: /usr/src/app/server/src
        - action: sync
          path: ../services/shared/src
          target: /usr/src/app/shared/src
  dev-client:
    build:
      context: ../services
      dockerfile: dev.Dockerfile
    working_dir: /usr/src/app/client
    command: npm run dev
    container_name: dev-client
    network_mode: host
    develop:
      watch:
        - action: sync
          path: ../services/client/src
          target: /usr/src/app/client/src
          ignore:
            - routes.gen.tsx
        - action: sync
          path: ../services/shared/src
          target: /usr/src/app/shared/src
    volumes:
      - ../services/client/src/routes.gen.tsx:/usr/src/app/client/src/routes.gen.tsx

volumes:
  devdb:
