services:
  dev-db-all:
    image: cockroachdb/cockroach:v24.3.0
    container_name: dev-db-all
    environment:
      - COCKROACH_USER=root
      - COCKROACH_PASSWORD=password
      - COCKROACH_DATABASE=db-dev-all
    volumes:
      - devdball:/cockroach/cockroach-data
    command: start-single-node --insecure
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "cockroach sql --insecure --host=dev-db-all --execute 'SELECT 1'",
        ]
      interval: 5s
      timeout: 5s
      retries: 12
  dev-app-all:
    build: ../services
    container_name: dev-app-all
    ports:
      - "127.0.0.1:3005:3005"
    depends_on:
      dev-db-all:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://root:password@dev-db-all:26257/db-dev-all?schema=public"
      NODE_ENV: test
      PORT: 3005
      AUTH_SECRET: "abcdefghi"
      CLIENT_URL: "http://localhost:3005"
      COOKIE_SECRET: "jklmnopq"
      CSRF_SECRET: "rstuvwxyz"
      SENTRY_AUTH_TOKEN: "DisabledWithNodeEnvTest"

volumes:
  devdball:
