services:
  lighthouse:
    image: femtopixel/google-lighthouse:v12.2.2@sha256:8fc18c53e53fd96d1c110fa23ca282f76a85f6fdacea94fa46a2a409a38aebcc
    command: ["http://localhost:3005"]
    volumes:
      - ../test/site-analyzer/reports:/home/chrome/reports
    user: root
    network_mode: host
