services:
  dev-db-all:
    extends:
      file: ./docker-compose.all.yml
      service: dev-db-all
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
  dev-app-all:
    extends:
      file: ./docker-compose.all.yml
      service: dev-app-all
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M

volumes:
  devdball:
