services:
  dev-db:
    image: cockroachdb/cockroach:v24.3.0
    container_name: dev-db
    ports:
      - '127.0.0.1:5433:26257'
    environment:
      - COCKROACH_USER=root
      - COCKROACH_PASSWORD=password
      - COCKROACH_DATABASE=dbdev
    command: start-single-node --insecure
    volumes:
      - devdb:/cockroach/cockroach-data

volumes:
  devdb:
