services:
  dev-db-all:
    image: postgres:17.0-alpine3.20
    container_name: dev-db-all
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    user: postgres
    volumes:
      - devdball:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h dev-db-all"]
      interval: 5s
      timeout: 5s
      retries: 5
  dev-app-all:
    build: ../services
    container_name: dev-app-all
    ports:
      - "127.0.0.1:3005:3005"
    depends_on:
      dev-db-all:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:password@dev-db-all:5432/db-dev?schema=public"
      NODE_ENV: test
      PORT: 3005
      AUTH_SECRET: "abcdefghi"
      CLIENT_URL: "http://localhost:3005"
      COOKIE_SECRET: "jklmnopq"
      CSRF_SECRET: "rstuvwxyz"
      SENTRY_AUTH_TOKEN: "DisabledWithNodeEnvTest"

volumes:
  devdball:
