name: Heroku deploy flow

on:
  workflow_call:

jobs:
  heroku-deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Heroku deploy
        uses: akhileshns/heroku-deploy@v4
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

          # Required for Heroku docker
          stack: container
          usedocker: true

          # Docker build context
          appdir: "services"
          docker_build_args: |
            SENTRY_AUTH_TOKEN
            SENTRY_ORG
            SENTRY_PROJECT

          # Health check
          healthcheck: "https://fs-project-41e16305e0df.herokuapp.com/api/healthz"
          checkstring: "ok"
          delay: 30
          rollbackonhealthcheckfailed: true
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
