name: Main flow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, ready_for_review]

jobs:
  smoke-test:
    uses: ./.github/workflows/smoke-test.yml
    if: ${{ !github.event.pull_request.draft }}
  stress-test:
    uses: ./.github/workflows/stress-test.yml
    needs: ['smoke-test']
  site-analyzer:
    uses: ./.github/workflows/site-analyzer.yml
    needs: ['smoke-test']
  deploy:
    uses: ./.github/workflows/heroku-deploy.yml
    needs: ['stress-test', 'site-analyzer']
    secrets: inherit
