name: Main flow

on:
  push:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  smoke-test:
    uses: ./.github/workflows/smoke-test.yml
    if: ${{ !github.event.pull_request.draft }}
  deploy:
    uses: ./.github/workflows/heroku-deploy.yml
    needs: ["smoke-test"]
    secrets: inherit
