name: Site Analyzer flow

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: compose up server
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: docker/docker-compose.all.yml
          up-flags: "-d --build"
          down-flags: "-v"

      - name: wait for health check
        uses: emilioschepis/wait-for-endpoint@v1.0.4
        with:
          url: http://localhost:3005/api/healthz
          method: GET
          expected-status: 200
          timeout: 60000
          interval: 1000

      - name: analyze url
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            http://localhost:3005
          configPath: "test/site-analyzer/lighthouserc.cjs"
          uploadArtifacts: true
