name: Smoke test Flow

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install root
        run: |
          npm ci
          npm run prettier:check

      - name: install services
        run: |
          cd services
          npm ci

      - name: run shared smoke tests
        run: |
          cd services/shared
          npx tsc --noEmit
          npm run lint:check

      - name: run server smoke tests
        run: |
          cd services/server
          npx prisma generate
          npx tsc --emitDeclarationOnly
          npx tsc-alias
          npm run lint:check

      - name: run client smoke tests
        run: |
          cd services/client
          npx tsc -b --noEmit
          npm run lint:check

      - name: Run stress test smoke tests
        run: |
          cd test/stress-test
          npm ci
          npx tsc --noEmit
          npm run lint:check
