name: Smoke test Flow

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run server smoke tests
        run: |
          cd services/server
          npm ci
          npm run build
          npm run lint:check
          npm run prettier:check

      - name: run client smoke tests
        run: |
          cd services/client
          npm ci
          npm run build
          npm run lint:check
          npm run prettier:check

      - name: Run stress test smoke tests
        run: |
          cd test/stress-test
          npm ci
          npm run build
          npm run lint:check
          npm run prettier:check
