name: Smoke test flow

on:
  workflow_call:

jobs:
  smoke-test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Run server smoke tests
        run: |
          cd services/server
          npm ci
          npm run build
          npm run lint:check
          npm run prettier:check

      - name: Run client smoke tests
        run: |
          cd services/client
          npm ci
          npm run build
          npm run lint:check
          npm run prettier:check

      - name: Run stress test smoke tests
        run: |
          cd test/stress-test
          npm ci
          npm run build
          npm run lint:check
          npm run prettier:check
