name: Stress test flow

on:
  workflow_call:

jobs:
  smoke-test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Compose up server
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: dev/docker-compose.dev-full.yml
          up-flags: "-d --build"
          down-flags: "-v"

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: "0.54.0"

      - name: Run K6
        uses: grafana/run-k6-action@v1
        env:
          BASE_URL: http://localhost:3005
        with:
          path: |
            ./test/stress-test/src/test.ts
          flags: --compatibility-mode experimental_enhanced
          inspect-flags: --compatibility-mode experimental_enhanced
